#!/usr/bin/env python3
"""Generate TRMNL private-plugin artifacts from data/diet-plan.json.

Outputs:
  dist/markup.liquid  -> generic Liquid template; paste ONCE into the private
                         plugin's Full layout. Contains no diet data.
  dist/data.json      -> the diet data; paste into the plugin's Static Data
                         field (or host it and use the Polling strategy).
                         Update the plan by re-pasting only this file.
  preview/index.html  -> local 800x480 preview, rendered through the real
                         Liquid template (requires: pip install python-liquid)
"""

import datetime as dt
import json
import os
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# Vendored locally (gitignored) so the preview works offline / in sandboxed browsers.
FRAMEWORK_CSS_URL = "https://trmnl.com/css/latest/plugins.css"
FRAMEWORK_JS_URL = "https://trmnl.com/js/latest/plugins.js"
FRAMEWORK_CSS = "vendor/plugins.css"
FRAMEWORK_JS = "vendor/plugins.js"

CARD_IDLE = "bg--white"
CARD_ACTIVE = "bg--yellow"
LABEL_ACTIVE = "label--error"
CARD_CSS = "<style>.meal-card { border: 2px solid #000; }</style>"

IST = 19800  # +05:30, used only for preview rendering

# The one and only screen definition. Data arrives as TRMNL merge variables
# (top-level keys of dist/data.json: meta, slots, days). The data-slot /
# data-role attributes are inert on the device; the local preview's JS uses
# them to simulate other times of day.
TEMPLATE = f"""{{% comment %}}
  Diet Plan — generic template, generated by scripts/build.py.
  Data lives in the plugin's Static Data field (see dist/data.json).
  Day 1 = Monday, repeats weekly. Times localized via trmnl.user.utc_offset.
{{% endcomment %}}
{CARD_CSS}
{{% assign local_ts = "now" | date: "%s" | plus: trmnl.user.utc_offset %}}
{{% assign dow = local_ts | date: "%u" | plus: 0 %}}
{{% assign hm = local_ts | date: "%H%M" | plus: 0 %}}
{{% assign day_idx = dow | minus: 1 %}}
{{% assign day = days[day_idx] %}}
{{% assign active_slot = slots.first.key %}}
{{% for s in slots %}}{{% if hm >= s.start %}}{{% assign active_slot = s.key %}}{{% endif %}}{{% endfor %}}
<div class="layout layout--col gap--small">
  <div class="flex flex--row flex--between flex--center-y">
    <span class="value value--large">{{{{ day.weekday }}}}</span>
    <div class="flex flex--col text--right">
      <span class="value value--small">Day {{{{ day.day }}}} of 7 &middot; {{{{ day.kcal_text }}}}</span>
      <span class="label label--small">{{{{ meta.reminders }}}}</span>
    </div>
  </div>
  <div class="grid grid--cols-3 gap--small stretch-y">
    {{% for s in slots %}}
    {{% assign items = day.meals[s.key] %}}
    <div class="meal-card flex flex--col gap--xsmall p--3 rounded--small {{% if s.key == active_slot %}}{CARD_ACTIVE}{{% else %}}{CARD_IDLE}{{% endif %}}" data-slot="{{{{ s.key }}}}">
      <span class="label label--small {{% if s.key == active_slot %}}{LABEL_ACTIVE}{{% endif %}}" data-role="slot-label">{{{{ s.name | upcase }}}} &middot; {{{{ s.time }}}}</span>
      {{% for item in items %}}
      <div class="flex flex--row flex--between gap--small w--full">
        <span class="text--small">{{{{ item.food }}}}</span>
        <span class="text--small"><strong>{{{{ item.portion }}}}</strong></span>
      </div>
      {{% endfor %}}
    </div>
    {{% endfor %}}
  </div>
  <div class="flex flex--row flex--center-x w--full">
    <span class="label label--small">{{{{ meta.legend }}}}</span>
  </div>
</div>
<div class="title_bar">
  <span class="title">{{{{ meta.title }}}}</span>
  <span class="instance">Day {{{{ day.day }}}} &middot; {{{{ day.weekday }}}}</span>
</div>
"""


def build_data(plan: dict) -> dict:
    """The merge-variable payload: the plan plus derived display fields."""
    data = json.loads(json.dumps(plan))  # deep copy
    for day in data["days"]:
        day["kcal_text"] = f"~{day['kcal']:,} kcal"
    return data


def render_preview_days(data: dict) -> list:
    """Render the real template once per weekday via python-liquid, the way
    TRMNL's UTC servers would (noon local time; the preview JS re-applies the
    active-slot highlight client-side)."""
    from liquid import Environment

    old_tz = os.environ.get("TZ")
    os.environ["TZ"] = "UTC"  # TRMNL renders on UTC servers; match them
    time.tzset()
    try:
        env = Environment()
        monday = dt.datetime(2026, 7, 20, 12, 0)  # any Monday works
        out = []
        for i in range(7):
            local = monday + dt.timedelta(days=i)
            epoch = int(
                (local - dt.timedelta(seconds=IST))
                .replace(tzinfo=dt.timezone.utc)
                .timestamp()
            )
            patched = TEMPLATE.replace('"now" | date: "%s"', str(epoch))
            html = env.from_string(patched).render(
                trmnl={"user": {"utc_offset": IST}}, **data
            )
            out.append(html)
        return out
    finally:
        if old_tz is None:
            del os.environ["TZ"]
        else:
            os.environ["TZ"] = old_tz
        time.tzset()


def build_preview(data: dict, day_htmls: list) -> str:
    slots_json = json.dumps(
        [{"key": s["key"], "start": s["start"]} for s in data["slots"]]
    )
    day_sections = "\n".join(
        f'<div data-day="{i + 1}" style="display:none">\n'
        f'<div class="view view--full">\n{html}\n</div>\n</div>'
        for i, html in enumerate(day_htmls)
    )
    return f"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Diet TRMNL preview (800x480)</title>
<link rel="stylesheet" href="{FRAMEWORK_CSS}">
<script src="{FRAMEWORK_JS}"></script>
<style>
  body {{ background: #ddd !important; margin: 0; padding: 24px; font-family: sans-serif; }}
  .frame {{ width: 800px; margin: 0 auto; }}
  .controls {{ width: 800px; margin: 0 auto 12px; display: flex; gap: 8px; align-items: center; }}
  .controls button {{ padding: 4px 10px; }}
  .controls button.on {{ background: #000; color: #fff; }}
</style>
</head>
<body class="environment trmnl">
<div class="controls">
  <span>Day:</span>
  <span id="daybtns"></span>
  <label>Time: <input id="time" type="time" value="12:30"></label>
</div>
<div class="frame">
  <div class="screen screen--ogv2 screen--color-4bwry">
{day_sections}
  </div>
</div>
<script>
const SLOTS = {slots_json};
const CARD_IDLE = "{CARD_IDLE}", CARD_ACTIVE = "{CARD_ACTIVE}";
const LABEL_ACTIVE = "{LABEL_ACTIVE}".split(" ");

function activeSlot(hm) {{
  let active = SLOTS[0].key;
  for (const s of SLOTS) if (hm >= s.start) active = s.key;
  return active;
}}

function apply(day, hm) {{
  document.querySelectorAll("[data-day]").forEach(v => v.style.display = v.dataset.day == day ? "" : "none");
  const act = activeSlot(hm);
  document.querySelectorAll("[data-slot]").forEach(card => {{
    const on = card.dataset.slot === act;
    card.classList.toggle(CARD_ACTIVE, on);
    card.classList.toggle(CARD_IDLE, !on);
    const label = card.querySelector('[data-role="slot-label"]');
    LABEL_ACTIVE.forEach(c => label.classList.toggle(c, on));
  }});
  document.querySelectorAll("#daybtns button").forEach(b => b.classList.toggle("on", b.textContent == day));
}}

const now = new Date();
let day = ((now.getDay() + 6) % 7) + 1;  // Mon=1..Sun=7
const btns = document.getElementById("daybtns");
for (let i = 1; i <= 7; i++) {{
  const b = document.createElement("button");
  b.textContent = i;
  b.onclick = () => {{ day = i; refresh(); }};
  btns.appendChild(b);
}}
const timeInput = document.getElementById("time");
timeInput.value = String(now.getHours()).padStart(2, "0") + ":" + String(now.getMinutes()).padStart(2, "0");
timeInput.oninput = refresh;
function refresh() {{
  const hm = parseInt(timeInput.value.replace(":", ""), 10) || 0;
  apply(day, hm);
}}
refresh();
</script>
</body>
</html>
"""


def vendor_framework(preview: Path):
    vendor = preview / "vendor"
    vendor.mkdir(exist_ok=True)
    import re
    from urllib.request import Request, urlopen

    def fetch(url: str) -> bytes:
        req = Request(url, headers={"User-Agent": "diet-trmnl-preview"})
        with urlopen(req) as resp:
            return resp.read()

    for url, name in [(FRAMEWORK_CSS_URL, "plugins.css"), (FRAMEWORK_JS_URL, "plugins.js")]:
        dest = vendor / name
        if not dest.exists():
            print(f"downloading {url} ...")
            dest.write_bytes(fetch(url))

    # The CSS references fonts at /fonts/... — vendor them too and make the
    # paths relative, otherwise the preview falls back to Times New Roman.
    css_path = vendor / "plugins.css"
    css = css_path.read_text()
    font_names = sorted(set(re.findall(r'url\("/fonts/([^"]+)"\)', css)))
    if font_names:
        fonts_dir = vendor / "fonts"
        fonts_dir.mkdir(exist_ok=True)
        for fname in font_names:
            fdest = fonts_dir / fname
            if not fdest.exists():
                print(f"downloading font {fname} ...")
                fdest.write_bytes(fetch(f"https://trmnl.com/fonts/{fname}"))
        css_path.write_text(css.replace('url("/fonts/', 'url("fonts/'))


def main():
    # Private plan is gitignored; fresh clones build from the example.
    src = ROOT / "data" / "diet-plan.json"
    if not src.exists():
        src = ROOT / "data" / "diet-plan.example.json"
        print(f"note: using {src.name} (create data/diet-plan.json for your own plan)")
    plan = json.loads(src.read_text())
    dist = ROOT / "dist"
    preview = ROOT / "preview"
    dist.mkdir(exist_ok=True)
    preview.mkdir(exist_ok=True)
    vendor_framework(preview)

    data = build_data(plan)
    (dist / "markup.liquid").write_text(TEMPLATE)
    (dist / "data.json").write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    )
    print(f"dist/markup.liquid: {len(TEMPLATE):,} bytes (template, paste once)")
    print(f"dist/data.json: {(dist / 'data.json').stat().st_size:,} bytes (static data)")

    try:
        day_htmls = render_preview_days(data)
    except ImportError:
        print("python-liquid not installed -> preview NOT regenerated "
              "(pip install python-liquid)")
        return
    (preview / "index.html").write_text(build_preview(data, day_htmls))
    print("preview/index.html written (rendered through the real template)")


if __name__ == "__main__":
    main()
